# Generated by Django 4.1.1 on 2022-09-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='realtors',
            new_name='realtor',
        ),
    ]
